version: 2.1

executors:
  go:
    docker:
      - image: cimg/go:1.15

workflows:
  build_and_publish:
    jobs:
      - build_and_publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  build_and_publish:
    executor: go
    steps:
      - checkout:
          path: ./WhisperLogs2
      - run:
          name: Build artifact
          command: |
            rm -rf ./WhisperLogs2/assets
            zip -r WhisperLogs2.zip ./WhisperLogs2
            mv WhisperLogs2.zip ./WhisperLogs2/WhisperLogs2-$CIRCLE_TAG.zip
      - run:
          name: Install dependencies
          command: |
            go get github.com/ericchiang/pup
      - run:
          name: Upload artifact
          command: |
            cd ./WhisperLogs2
            bash .circleci/upload.sh ./WhisperLogs2-$CIRCLE_TAG.zip
